includes = []
# packages = [
#   "zsh",
#   "bash",
#   "xonsh",
#   "nvim",
#   "fish",
#   "editor",
#   "fd",
#   "aliases",
#   "starship",
#   "zed"
# ]

[files]
# "dotter.sh" = "~/bin/dotter"

[variables]
# open_ai_key =
