[helpers]

[default]
depends = []

[default.files]
xonsh = ""

[default.variables]

[zsh]

[zsh.files."zsh/zshrc"]
target = "~/.zshrc"
type = "template"

[zsh.variables]
zsh_home = "~/.dotfiles/zsh"

[bash]

[bash.files."bash/bashrc"]
target = "~/.bashrc"
type = "symbolic"

[bash.files."bash/bash_aliases"]
target = "~/.bash_aliases"
type = "symbolic"

[xonsh]

[xonsh.files."xonsh/xonshrc"]
target = "~/.xonshrc"
type = "template"

[nvim]

[nvim.files]
"nvim/lua" = "~/.config/nvim/lua"
"nvim/site" = "~/.local/share/nvim/site"
"nvim/vim_conf" = "~/.config/nvim/vim_conf"
"nvim/.neoconf.json" = "~/.config/nvim/.neoconf.json"
"nvim/init.lua" = "~/.config/nvim/init.lua"
"nvim/lazyvim.json" = "~/.config/nvim/lazyvim.json"
"nvim/stylua.toml" = "~/.config/nvim/stylua.toml"

[fish]

[fish.files.fish]
target = "~/.config/fish"
type = "symbolic"

[editor]

[editor.files]
editorconfig = "~/.editorconfig"

[fd]

[fd.files]
fdignore = "~/.config/fd/ignore"

[aliases]

[aliases.files]
"global_aliases.sh" = "~/.global_aliases"
